config/routes.rb
Rails.application.routes.draw do
  get 'products', to: 'products#index'
  get 'products/favourites', to: 'products#favourites' , as: 'favourites'
  post 'products', to: 'products#create'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch 'products/:id', to: 'products#update', as: 'update_product'
  patch 'products/:id/set_favourite', to: 'products#set_favourite',as: 'set_favourite'

  resources :products, only:[:create,:destroy]
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products, only: [:show, :edit, :update, :destroy, :set_favourite]
 def index
  @product = Product.new
  @products = Product.all
 end

def create
  @product = Product.new(products_params)
  @product.save
  redirect_to product_path(@product.id)
end
def show
end
def edit
end
def update
  @product.update(products_params)
  redirect_to products_path
end
def destroy
 @product.destroy
 redirect_to products_path
end
def set_favourite
@product.favourite = true
@product.save
redirect_to favourites_path
end
def favourites
  @product = Product.where(favourite: true)
end
private
def products_params
 params.require(:product).permit(:name, :price, :description, :image, :favourite)
end
def set_products
 @product = Product.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PreparacionPrueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/navbar'%>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partial/_navbar.html.erb
<nav class="navbar fixed-top  navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Products</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path%>">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= favourites_path%>">Favourites</a>
      </li>
    </ul>
  </div>
</nav

app/views/products/edit.html.erb
<div class="row">
  <div class="col col-md-6">
    <div class="col col-md-4">
      <%= form_with(model: @product, local:true) do |form| %>
        <%= form.label :name%>
        <%= form.text_field :name, class:'form-control'%> <br>
        <%= form.label :price%>
        <%= form.number_field :price, class:'form-control' %><br>
        <%= form.label :description %>
        <%= form.text_area :description, class:'form-control' %><br>
        <%= form.label :image %>
        <%= form.text_field :image, class:'form-control' %><br>
        <%= form.submit 'Enviar', class: 'btn btn-success'%>
      <% end %>
  </div>
</div>
<%= link_to 'back', products_path%>

app/views/products/favourites.html.erb
<div class="row">
  <div class="col col-md-8">
    <table class="table table-hover">
     <tr>
       <th>Name</th>
       <th>Price</th>
       <th>Description</th>
       <th>Image</th>
     </tr>
     <% @product.each do |product|%>
     <tr>
       <td><%= product.name %></td>
       <td><%= product.price %></td>
       <td><%= product.description %></td>
       <td><%= image_tag product.image, width: '100px'%></td>

      </tr>
      <% end %>
    </table>

  </div>

app/views/products/index.html.erb
<div class="row">
  <div class="col col-md-8">
    <table class="table table-hover"">
     <tr>
       <th>Name</th>
       <th>Price</th>
       <th>Description</th>
     </tr>
     <% @products.each do |product|%>
     <tr>
       <td><%= product.name %></td>
       <td><%= product.price %></td>
       <td><%= product.description %></td>
       <td><%=link_to 'show', product_path(product.id),class: 'btn btn-success' %></td>
       <td><%=link_to 'edit', edit_product_path(product.id),class: 'btn btn-warning' %></td>
       <td><%=link_to 'delete', product_path(product.id), method: :delete ,class: 'btn btn-danger'%></td>
       <td><%=link_to 'favourite', set_favourite_path(product.id),method: :patch,class: 'btn btn-warning'%></td>

      </tr>
      <% end %>
    </table>

  </div>
  <div class="col col-md-4">
    <%= form_with(model: @product, local:true) do |form| %>
      <%= form.label :name%>
      <%= form.text_field :name, class:'form-control'%> <br>
      <%= form.label :price%>
      <%= form.number_field :price, class:'form-control' %><br>
      <%= form.label :description %>
      <%= form.text_area :description, class:'form-control' %><br>
      <%= form.label :image %>
      <%= form.text_field :image, class:'form-control' %><br>
      <%= form.submit 'Enviar', class: 'btn btn-success'%>
    <% end %>
  </div>

</div>

app/views/products/show.html.erb
<h5>Name:</h5>
<%= @product.name%>
<h5>Price:</h5>
<%= @product.price%>
<h5>Description:</h5>
<%= @product.description%>
<h5>Favourite</h5>
<%= @product.favourite %>
<h5>Image:</h5>
<%= image_tag @product.image,width: '100px'%>



<%= link_to 'back', products_path, class: 'btn btn-success'%>